{
 "title": "MLTools dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Execution Time / Experiments",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT e.name AS experiment_name, AVG(r.end_time - r.start_time) AS avg_execution_time\r\nFROM experiments e\r\nJOIN runs r ON e.experiment_id = r.experiment_id\r\nWHERE r.end_time IS NOT NULL\r\nGROUP BY e.name\r\nORDER BY avg_execution_time DESC;"
    }
   ]
  },
  {
   "title": "MEMORY usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nb de request http 200 ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"fastapi_app\", instance=\"fastapi_app:8000\", status=\"2xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy / Runs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT r.run_uuid, m.key AS metric_name, m.value\r\nFROM metrics m\r\nJOIN runs r ON r.run_uuid = m.run_uuid\r\nWHERE m.key IN ('accuracy')\r\nORDER BY m.key, r.start_time;"
    }
   ]
  },
  {
   "title": "Nb request / 5min ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"fastapi_app\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NB d'exécutions par expérimentation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT e.name AS experiment_name, COUNT(r.run_uuid) AS total_runs\r\nFROM experiments e\r\nLEFT JOIN runs r ON e.experiment_id = r.experiment_id\r\nGROUP BY e.name\r\nORDER BY total_runs DESC;"
    }
   ]
  },
  {
   "title": "status des experimentations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT e.name AS experiment_name, r.status, r.artifact_uri\r\nFROM experiments e\r\nJOIN runs r ON e.experiment_id = r.experiment_id\r\nWHERE r.start_time IS NOT NULL\r\nORDER BY r.start_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Erreurs par endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps de réponse moyen par endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nb request / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}